"use client";
import { useEffect,useState } from "react";

export default function AuthGate({onSuccess}:{onSuccess:()=>void}){
 const [mode,setMode]=useState<"login"|"register"|"reset-request"|"reset">("login"),[address,setAddress]=useState(""),[password,setPassword]=useState(""),[setupKey,setSetupKey]=useState(""),[invite,setInvite]=useState(""),[resetToken,setResetToken]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{const params=new URLSearchParams(location.search);if(params.has("invite")){setMode("register");setInvite(params.get("invite")||"");setAddress(params.get("email")||"")}else if(params.has("reset")){setMode("reset");setResetToken(params.get("reset")||"")}},[]);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage("");try{const r=await fetch("/api/auth",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:mode,email:address,password,setupKey,inviteToken:invite,token:resetToken})});const response=await r.json() as {error?:string;message?:string};if(!r.ok)throw Error(response.error||"Try again.");if(mode==="reset-request"){setMessage(response.message||"Check your email.");return}if(mode==="reset"){history.replaceState({},"","/");setMode("login");setPassword("");setMessage("Password changed. Sign in now.");return}history.replaceState({},"","/");onSuccess()}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 return <main className="auth-shell"><img src="/app-icon.png" alt="Our World logo" width="68" height="68"/><h1>Our World</h1><p>A private map for Li and Fiona.</p><form className="surface auth-card form-stack" onSubmit={submit}><h2>{mode==="login"?"Sign in":mode==="register"?invite?"Accept your invitation":"Create Li’s account":mode==="reset"?"Choose a new password":"Reset your password"}</h2>{mode!=="reset"&&<label>Email<input type="email" required value={address} onChange={e=>setAddress(e.target.value)} autoComplete="email"/></label>}{mode!=="reset-request"&&<label>{mode==="reset"?"New password":"Password"}<input type="password" required minLength={12} value={password} onChange={e=>setPassword(e.target.value)} autoComplete={mode==="login"?"current-password":"new-password"}/></label>}{mode==="register"&&!invite&&<label>Owner setup code<input type="password" required value={setupKey} onChange={e=>setSetupKey(e.target.value)} autoComplete="off"/></label>}{message&&<p className="auth-message" role="status">{message}</p>}<button className="main-action" type="submit" disabled={busy}>{busy?"Please wait…":mode==="login"?"Sign in":mode==="register"?"Create account":mode==="reset"?"Save password":"Send reset link"}</button><div className="auth-links">{mode!=="login"&&<button type="button" onClick={()=>{setMode("login");setMessage("")}}>Sign in</button>}{mode==="login"&&<><button type="button" onClick={()=>{setMode("reset-request");setMessage("")}}>Forgot password?</button><button type="button" onClick={()=>{setMode("register");setMessage("")}}>Set up Li’s account</button></>}</div></form></main>
}
